benchmarks:
- benchmark_name: "single_chip_hbm_copy"
  benchmark_sweep_params:
  - {m: 1024, k: 1024, n: 1024}
  - {m: 2048, k: 2048, n: 2048}
  - {m: 4096, k: 4096, n: 4096}
  - {m: 8192, k: 8192, n: 8192}
  - {m: 16384, k: 16384, n: 16384}
  - {m: 32768, k: 32768, n: 32768}
  - {m: 65536, k: 65536, n: 65536}
  trace_dir: "/tmp/microbenchmarks/matmul"
  csv_path: "/tmp/microbenchmarks/matmul"
  xlml_metrics_dir: "/tmp/microbenchmarks/matmul"
- benchmark_name: "single_host_naive_matmul"
  benchmark_sweep_params:
  - {m: 1024, k: 1024, n: 1024}
  - {m: 2048, k: 2048, n: 2048}
  - {m: 4096, k: 4096, n: 4096}
  - {m: 8192, k: 8192, n: 8192}
  - {m: 16384, k: 16384, n: 16384}
  - {m: 32768, k: 32768, n: 32768}
  - {m: 65536, k: 65536, n: 65536}
  trace_dir: "/tmp/microbenchmarks/matmul"
  csv_path: "/tmp/microbenchmarks/matmul"
  xlml_metrics_dir: "/tmp/microbenchmarks/matmul"
- benchmark_name: "multilayer_collective_matmul"
  benchmark_sweep_params:
  - {m: 1024, k: 1024, n: 1024}
  - {m: 2048, k: 2048, n: 2048}
  - {m: 4096, k: 4096, n: 4096}
  - {m: 8192, k: 8192, n: 8192}
  - {m: 16384, k: 16384, n: 16384}
  - {m: 32768, k: 32768, n: 32768}
  - {m: 65536, k: 65536, n: 65536}
  trace_dir: "/tmp/microbenchmarks/matmul"
  csv_path: "/tmp/microbenchmarks/matmul"
  xlml_metrics_dir: "/tmp/microbenchmarks/matmul"
- benchmark_name: "collective_matmul_one_direction"
  benchmark_sweep_params:
  - {m: 1024, k: 1024, n: 1024}
  - {m: 2048, k: 2048, n: 2048}
  - {m: 4096, k: 4096, n: 4096}
  - {m: 8192, k: 8192, n: 8192}
  - {m: 16384, k: 16384, n: 16384}
  - {m: 32768, k: 32768, n: 32768}
  - {m: 65536, k: 65536, n: 65536}
  trace_dir: "/tmp/microbenchmarks/matmul"
  csv_path: "/tmp/microbenchmarks/matmul"
  xlml_metrics_dir: "/tmp/microbenchmarks/matmul"
- benchmark_name: "collective_matmul_two_directions"
  benchmark_sweep_params:
  - {m: 1024, k: 1024, n: 1024}
  - {m: 2048, k: 2048, n: 2048}
  - {m: 4096, k: 4096, n: 4096}
  - {m: 8192, k: 8192, n: 8192}
  - {m: 16384, k: 16384, n: 16384}
  - {m: 32768, k: 32768, n: 32768}
  - {m: 65536, k: 65536, n: 65536}
  trace_dir: "/tmp/microbenchmarks/matmul"
  csv_path: "/tmp/microbenchmarks/matmul"
